version: "3.9"

services:
  backend:
    container_name: app_backend
    build: ./back-end
    ports:
      - 3001:3001
    command: npm run db:start
    working_dir: /app-backend
    environment:
      - DB_USER=root
      - DB_PASS=123456
      - DB_NAME=cdr_db
      - DB_HOST=db
      - DB_PORT=3306
      - JWT_SECRET=jwtsecret
    depends_on:
      - db
    tty: true

  db:
    image: mysql:8.0.21
    container_name: db
    platform: linux/x86_64
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=cdr_db
    restart: 'always'